#############################################################################
# Makefile for building: QSoapExplorer
# Generated by qmake (2.01a) (Qt 4.6.2) on: Fri Apr 2 13:20:48 2010
# Project:  QSoapExplorer.pro
# Template: app
# Command: /home/dals/qtsdk/qt/bin/qmake -spec ../../../qtsdk/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QSoapExplorer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_SCRIPT_LIB -DQT_SCRIPTTOOLS_LIB -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../qtsdk/qt/mkspecs/linux-g++ -I. -I../../../qtsdk/qt/include/QtCore -I../../../qtsdk/qt/include/QtNetwork -I../../../qtsdk/qt/include/QtGui -I../../../qtsdk/qt/include/QtXml -I../../../qtsdk/qt/include/QtXmlPatterns -I../../../qtsdk/qt/include/QtScriptTools -I../../../qtsdk/qt/include/QtScript -I../../../qtsdk/qt/include/QtWebKit -I../../../qtsdk/qt/include -Ilib/qtsoap/src -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/dals/qtsdk/qt/lib
LIBS          = $(SUBLIBS)  -L/home/dals/qtsdk/qt/lib -lQtWebKit -L/home/dals/qtsdk/qt/lib -L/usr/X11R6/lib -lphonon -L/home/berlin/dev/qt-4.6.2-opensource-shipping/this_path_is_supposed_to_be_very_long_hopefully_this_is_long_enough/qt/lib -lQtDBus -lQtScriptTools -lQtScript -lQtXmlPatterns -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/dals/qtsdk/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = lib/qtsoap/src/qtsoap.cpp \
		main.cpp \
		qsoapexplorer.cpp moc_qtsoap.cpp \
		moc_qsoapexplorer.cpp
OBJECTS       = qtsoap.o \
		main.o \
		qsoapexplorer.o \
		moc_qtsoap.o \
		moc_qsoapexplorer.o
DIST          = ../../../qtsdk/qt/mkspecs/common/g++.conf \
		../../../qtsdk/qt/mkspecs/common/unix.conf \
		../../../qtsdk/qt/mkspecs/common/linux.conf \
		../../../qtsdk/qt/mkspecs/qconfig.pri \
		../../../qtsdk/qt/mkspecs/features/qt_functions.prf \
		../../../qtsdk/qt/mkspecs/features/qt_config.prf \
		../../../qtsdk/qt/mkspecs/features/exclusive_builds.prf \
		../../../qtsdk/qt/mkspecs/features/default_pre.prf \
		lib/qtsoap/common.pri \
		lib/qtsoap/src/qtsoap.pri \
		../../../qtsdk/qt/mkspecs/features/debug.prf \
		../../../qtsdk/qt/mkspecs/features/default_post.prf \
		../../../qtsdk/qt/mkspecs/features/warn_on.prf \
		../../../qtsdk/qt/mkspecs/features/qt.prf \
		../../../qtsdk/qt/mkspecs/features/unix/thread.prf \
		../../../qtsdk/qt/mkspecs/features/moc.prf \
		../../../qtsdk/qt/mkspecs/features/resources.prf \
		../../../qtsdk/qt/mkspecs/features/uic.prf \
		../../../qtsdk/qt/mkspecs/features/yacc.prf \
		../../../qtsdk/qt/mkspecs/features/lex.prf \
		../../../qtsdk/qt/mkspecs/features/include_source_dir.prf \
		QSoapExplorer.pro
QMAKE_TARGET  = QSoapExplorer
DESTDIR       = 
TARGET        = QSoapExplorer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_qsoapexplorer.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QSoapExplorer.pro  ../../../qtsdk/qt/mkspecs/linux-g++/qmake.conf ../../../qtsdk/qt/mkspecs/common/g++.conf \
		../../../qtsdk/qt/mkspecs/common/unix.conf \
		../../../qtsdk/qt/mkspecs/common/linux.conf \
		../../../qtsdk/qt/mkspecs/qconfig.pri \
		../../../qtsdk/qt/mkspecs/features/qt_functions.prf \
		../../../qtsdk/qt/mkspecs/features/qt_config.prf \
		../../../qtsdk/qt/mkspecs/features/exclusive_builds.prf \
		../../../qtsdk/qt/mkspecs/features/default_pre.prf \
		lib/qtsoap/common.pri \
		lib/qtsoap/src/qtsoap.pri \
		../../../qtsdk/qt/mkspecs/features/debug.prf \
		../../../qtsdk/qt/mkspecs/features/default_post.prf \
		../../../qtsdk/qt/mkspecs/features/warn_on.prf \
		../../../qtsdk/qt/mkspecs/features/qt.prf \
		../../../qtsdk/qt/mkspecs/features/unix/thread.prf \
		../../../qtsdk/qt/mkspecs/features/moc.prf \
		../../../qtsdk/qt/mkspecs/features/resources.prf \
		../../../qtsdk/qt/mkspecs/features/uic.prf \
		../../../qtsdk/qt/mkspecs/features/yacc.prf \
		../../../qtsdk/qt/mkspecs/features/lex.prf \
		../../../qtsdk/qt/mkspecs/features/include_source_dir.prf \
		/home/dals/qtsdk/qt/lib/libQtWebKit.prl \
		/home/dals/qtsdk/qt/lib/libphonon.prl \
		/home/dals/qtsdk/qt/lib/libQtDBus.prl \
		/home/dals/qtsdk/qt/lib/libQtXml.prl \
		/home/dals/qtsdk/qt/lib/libQtCore.prl \
		/home/dals/qtsdk/qt/lib/libQtGui.prl \
		/home/dals/qtsdk/qt/lib/libQtXmlPatterns.prl \
		/home/dals/qtsdk/qt/lib/libQtNetwork.prl \
		/home/dals/qtsdk/qt/lib/libQtScript.prl \
		/home/dals/qtsdk/qt/lib/libQtScriptTools.prl
	$(QMAKE) -spec ../../../qtsdk/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QSoapExplorer.pro
../../../qtsdk/qt/mkspecs/common/g++.conf:
../../../qtsdk/qt/mkspecs/common/unix.conf:
../../../qtsdk/qt/mkspecs/common/linux.conf:
../../../qtsdk/qt/mkspecs/qconfig.pri:
../../../qtsdk/qt/mkspecs/features/qt_functions.prf:
../../../qtsdk/qt/mkspecs/features/qt_config.prf:
../../../qtsdk/qt/mkspecs/features/exclusive_builds.prf:
../../../qtsdk/qt/mkspecs/features/default_pre.prf:
lib/qtsoap/common.pri:
lib/qtsoap/src/qtsoap.pri:
../../../qtsdk/qt/mkspecs/features/debug.prf:
../../../qtsdk/qt/mkspecs/features/default_post.prf:
../../../qtsdk/qt/mkspecs/features/warn_on.prf:
../../../qtsdk/qt/mkspecs/features/qt.prf:
../../../qtsdk/qt/mkspecs/features/unix/thread.prf:
../../../qtsdk/qt/mkspecs/features/moc.prf:
../../../qtsdk/qt/mkspecs/features/resources.prf:
../../../qtsdk/qt/mkspecs/features/uic.prf:
../../../qtsdk/qt/mkspecs/features/yacc.prf:
../../../qtsdk/qt/mkspecs/features/lex.prf:
../../../qtsdk/qt/mkspecs/features/include_source_dir.prf:
/home/dals/qtsdk/qt/lib/libQtWebKit.prl:
/home/dals/qtsdk/qt/lib/libphonon.prl:
/home/dals/qtsdk/qt/lib/libQtDBus.prl:
/home/dals/qtsdk/qt/lib/libQtXml.prl:
/home/dals/qtsdk/qt/lib/libQtCore.prl:
/home/dals/qtsdk/qt/lib/libQtGui.prl:
/home/dals/qtsdk/qt/lib/libQtXmlPatterns.prl:
/home/dals/qtsdk/qt/lib/libQtNetwork.prl:
/home/dals/qtsdk/qt/lib/libQtScript.prl:
/home/dals/qtsdk/qt/lib/libQtScriptTools.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../qtsdk/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QSoapExplorer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QSoapExplorer1.0.0 || $(MKDIR) .tmp/QSoapExplorer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QSoapExplorer1.0.0/ && $(COPY_FILE) --parents lib/qtsoap/src/qtsoap.h qsoapexplorer.h .tmp/QSoapExplorer1.0.0/ && $(COPY_FILE) --parents lib/qtsoap/src/qtsoap.cpp main.cpp qsoapexplorer.cpp .tmp/QSoapExplorer1.0.0/ && $(COPY_FILE) --parents qsoapexplorer.ui .tmp/QSoapExplorer1.0.0/ && (cd `dirname .tmp/QSoapExplorer1.0.0` && $(TAR) QSoapExplorer1.0.0.tar QSoapExplorer1.0.0 && $(COMPRESS) QSoapExplorer1.0.0.tar) && $(MOVE) `dirname .tmp/QSoapExplorer1.0.0`/QSoapExplorer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QSoapExplorer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qtsoap.cpp moc_qsoapexplorer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qtsoap.cpp moc_qsoapexplorer.cpp
moc_qtsoap.cpp: lib/qtsoap/src/qtsoap.h
	/home/dals/qtsdk/qt/bin/moc $(DEFINES) $(INCPATH) lib/qtsoap/src/qtsoap.h -o moc_qtsoap.cpp

moc_qsoapexplorer.cpp: qsoapexplorer.h
	/home/dals/qtsdk/qt/bin/moc $(DEFINES) $(INCPATH) qsoapexplorer.h -o moc_qsoapexplorer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qsoapexplorer.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qsoapexplorer.h
ui_qsoapexplorer.h: qsoapexplorer.ui
	/home/dals/qtsdk/qt/bin/uic qsoapexplorer.ui -o ui_qsoapexplorer.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

qtsoap.o: lib/qtsoap/src/qtsoap.cpp lib/qtsoap/src/qtsoap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtsoap.o lib/qtsoap/src/qtsoap.cpp

main.o: main.cpp qsoapexplorer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qsoapexplorer.o: qsoapexplorer.cpp qsoapexplorer.h \
		ui_qsoapexplorer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qsoapexplorer.o qsoapexplorer.cpp

moc_qtsoap.o: moc_qtsoap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtsoap.o moc_qtsoap.cpp

moc_qsoapexplorer.o: moc_qsoapexplorer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qsoapexplorer.o moc_qsoapexplorer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

